name: Compile and Push Image
description: 'Compile docker image and push with to ECR'

inputs:
  repository:
    description: "Name of repository on ecr"
    required: true
  dockerfile:
    description: "If use a custom dockerfile"
    required: false
    default: 'Dockerfile'
  build_args:
    description: "Pass custom parameters to build"
    required: false
    default: ''
outputs:
  ECR_URL:
    description: "The first output string"
    value: ${{ steps.build_push.outputs.ECR_URL }}

runs:
  using: "composite"
  steps:
    - name: Login to Amazon ECR
      id: login_ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        build-args: ${{ inputs.build_args }}
        push: true
        tags: 
          - ${{ steps.login_ecr.outputs.registry }}/${{ inputs.repository }}:latest
          - ${{ steps.login_ecr.outputs.registry }}/${{ inputs.repository }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - id: build_push
      shell: bash
      run: echo "ECR_URL=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT