name: Compile and Push Image
description: 'Compile docker image and push with to ECR'

inputs:
  repository:
    description: "Name of repository on ecr"
    required: true
  dockerfile:
    description: "If use a custom dockerfile"
    required: false
    default: 'Dockerfile'
  build_args:
    description: "Pass custom parameters to build"
    required: false
    default: ''
  image_tags:
    description: "Custom image tags to build"
    required: false
    default: |
      type=raw,value=${{ github.sha }}

outputs:
  ECR_URL:
    description: "URL of image on ECR"
    value: ${{ steps.meta.outputs.tags }}

runs:
  using: "composite"
  steps:
    - name: Login to Amazon ECR
      id: login_ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get Tags for Image
      id: metadata
      uses: docker/metadata-action@v3
      with:
        images: ${{ steps.login_ecr.outputs.registry }}/${{ inputs.repository }}
        tags: ${{ inputs.image_tags }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        build-args: ${{ inputs.build_args }}
        push: true
        file: ${{ inputs.dockerfile }}
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}