name: Code Artifact URL
description: 'Mount Code Artifact URL'
inputs:
  domain:
    description: "Domain of code artifact"
    required: true
  repository:
    description: "Name of repository on code artifact"
    required: true
  region:
    description: "Region of code artifact"
    required: false
    default: "us-east-1"

outputs:
  CODE_ARTIFACT_URL:
    description: "Code artifact url with access key"
    value: ${{ steps.login_code_artifact.outputs.CODE_ARTIFACT_URL }}

runs:
  using: "composite"
  steps:
    - id: login_code_artifact
      shell: bash
      run: |
        aws codeartifact login --tool pip --domain ${{ inputs.domain }} --repository ${{ inputs.repository }} --region ${{ inputs.region }}
        CODE_ARTIFACT_URL=$(cat ~/.config/pip/pip.conf | grep "index-url" | cut -d '=' -f2)
        echo "CODE_ARTIFACT_URL=${CODE_ARTIFACT_URL}" >> $GITHUB_OUTPUT
    
    - id: update_requirements
      shell: bash
      run: |
        IFS=',' read -ra ADDR <<< "${{ inputs.requirements-files }}"
        for i in "${ADDR[@]}"; do
          echo "$(echo '--extra-index-url ${{ steps.login_code_artifact.outputs.CODE_ARTIFACT_URL }}' | cat - "$i")" > "$i"
        done