name: Code Artifact URL
description: 'Mount Code Artifact URL'
inputs:
  domain:
    description: "Domain of code artifact"
    required: true
  repository:
    description: "Name of repository on code artifact"
    required: true
  region:
    description: "Region of code artifact"
    required: false
    default: "us-east-1"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        aws codeartifact login --tool pip --domain ${{ inputs.domain }} --repository ${{ inputs.repository }} --region ${{ inputs.region }}