name: Push to ECR
description: 'Compile docker image and push to ECR'

inputs:
  repository:
    description: "Name of repository on ecr"
    required: true
  dockerfile:
    description: "If use a custom dockerfile"
    required: false
    default: 'Dockerfile'
  build_args:
    description: "Pass custom parameters to build"
    required: false
    default: ''
  image_tags:
    description: "Custom image tags to build"
    required: false
    default: |
      type=raw,value=${{ github.sha }}
      type=raw,value=latest

outputs:
  tags:
    description: "URL of image on ECR"
    value: ${{ steps.metadata.outputs.tags }}
  registry:
    description: "ECR image path"
    value: ${{ steps.expose.outputs.repository }}

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: Docker base image
        path: /tmp
    
    - name: Load image
      shell: bash
      run: |
        docker load --input /tmp/docker_image.tar