name: Run Code Quality Tools
description: 'Run code quality tools on code'

on:
  workflow_call:
    inputs:
      requirements:
        description: 'Requirements to install'
        required: false
        default: -r requirements.txt
      app_folder:
        description: 'Folder to run'
        required: false
        default: ./apps
      isort:
        description: 'Run isort'
        default: true
      safety:
        description: 'Run safety'
        default: true
      xenon:
        description: 'Run xenon'
        default: true
      bandit:
        description: 'Run bandit'
        default: true
      prospector:
        description: 'Run prospector'
        default: true


jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: pip install ${{ inputs.requirements }}

    - name: Run isort
      if: inputs.isort
      run: isort . --check-only --diff

    - name: Run safety
      if: inputs.safety
      run: safety check ${{ inputs.requirements }}

    - name: Run xenon (Cyclomatic Complexity)
      if: inputs.xenon
      run: xenon --max-absolute B --max-modules A --max-average A ${{ inputs.app_folder }}

    - name: Run bandit
      if: inputs.bandit
      run: bandit -c profile-bandit.yml . -r -ll
    
    - name: Run Prospector
      if: inputs.prospector
      run: |
        cp .env.sample .env
        prospector --profile profile_prospector -X