name: Run Tests
description: 'Run code testing'

on:
  workflow_call:
    inputs:
      command:
        description: 'Command to run'
        required: true
        default: manage.py test
      requirements:
        description: 'Requirements to install'
        required: false
        default: -r requirements.txt

jobs:
  code-quality:
    name: Tests and Coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: pip install ${{ inputs.requirements }}

    - name: Run Test
      run: |
        cp .env.test .env
        coverage run -a ${{ inputs.command }}
        coverage report -i --fail-under 25
        coverage xml
        coverage html
    
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: 'rspec.xml'

    # - name: Code Coverage Summary Report
    #   uses: irongut/CodeCoverageSummary@v1.3.0
    #   with:
    #     filename: coverage.xml
    #     badge: true
    #     format: markdown
    #     hide_branch_rate: false
    #     hide_complexity: true
    #     output: both
    #     thresholds: '25 25'
    
    # - name: Add Coverage PR Comment
    #   uses: marocchino/sticky-pull-request-comment@v2
    #   if: github.event_name == 'pull_request'
    #   with:
    #     recreate: true
    #     path: code-coverage-results.md