name: Download and Load Image
description: 'Download and load docker image'

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: Docker base image
        path: /tmp
    
    - name: Load image
      shell: bash
      run: |
        docker load --input /tmp/docker_image.tar