name: Run in Container
description: 'Run commands inside a container'

inputs:
  command:
    description: "Run command"
    required: true
  docker_parameters:
    description: "Run command"
    required: false
    default: ''
  REGISTRY_URL:
    description: "ECR URL of image to set in zappa"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run command
      shell: bash
      env:
        REGISTRY_URL: ${{ inputs.REGISTRY_URL }}
        PARAMS: ${{ inputs.docker_parameters }}
        COMMAND: ${{ inputs.command }}
      run: |
        docker run $PARAMS -e COMMAND='${{ inputs.command }}' -e REGISTRY_URL=$REGISTRY_URL --entrypoint '' $REGISTRY_URL sh -c 'eval $COMMAND'