name: Run Code Quality Tools
description: 'Run code quality tools on code'

inputs:
  build_command:
    description: 'Command to build project ex: (yarn build)'
    required: true
  bucket_name:
    description: 'S3 Bucket name'
    required: true
  auth_token:
    description: 'Auth token for private npm packages'
    default: ''
  aws_region:
    description: 'AWS region'
    required: true
  aws_access_key_id:
    description: 'AWS ACCESS_KEY_ID'
    required: true
  aws_secret_access_key:
    description: 'AWS SECRET_ACCESS_KEY'
    required: true

runs:
  using: "composite"
  steps:
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        registry-url: https://npm.pkg.github.com
        # cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: yarn
      env:
        NODE_AUTH_TOKEN: ${{ inputs.auth_token }}

    - name: Build project
      shell: bash
      run: ${{ inputs.build_command }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}

    - name: Deploy files to S3 bucket (out)
      shell: bash
      run: aws s3 sync .out/ s3://${{ inputs.bucket_name }}/ --delete

    - name: Deploy files to S3 bucket
      shell: bash
      run: aws s3 sync .next/ s3://${{ inputs.bucket_name }}/ --delete


  # - name: Invalidate current CloudFront  # think about how to get this dynamic
  #   shell: bash
  #   run: aws cloudfront create-invalidation --distribution-id ${{ inputs.cloudfront_id }} --paths "/*"