name: Set env
description: 'Set env only if is correct branch'

inputs:
  branch:
    description: "Name of branch name"
    required: false
    default: ''
  AWS_ACCESS_KEY_ID:
    description: "AWS_ACCESS_KEY_ID"
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: "AWS_SECRET_ACCESS_KEY"
    required: true

runs:
  using: "composite"
  steps:
    - id: set_env
      if: |
        github.ref_name == ${{ inputs.branch }} || 
        (github.event_name == 'pull_request' && github.head_ref == ${{ inputs.branch }})
      name: Set environment if is correct branch
      shell: bash
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ inputs.AWS_ACCESS_KEY_ID }}" >> "$GITHUB_ENV"
        echo "AWS_SECRET_ACCESS_KEY=${{ inputs.AWS_SECRET_ACCESS_KEY }}" >> "$GITHUB_ENV"