name: Set env
description: 'Set env only if is correct branch'

inputs:
  branch:
    description: "Name of branch name"
    required: false
    default: ''
  variables:
    description: "Variables to set if is current branch"
    required: false

runs:
  using: "composite"
  steps:
    - id: set_env
      if: github.ref == ${{ inputs.branch }}
      name: Set environment if is correct branch
      shell: bash
      run: |
        IFS=';' read -r -a array <<< ${{ inputs.variables }}
        for element in "${array[@]}"
        do
            echo "$element" >> "$GITHUB_ENV"
        done