name: Set Environment

on:
  workflow_call:
    outputs:
      BRANCH:
        description: "BRANCH"
        value: ${{ jobs.set-env.outputs.BRANCH }}
      CLUSTER:
        description: "CLUSTER"
        value: ${{ jobs.set-env.outputs.CLUSTER }}

jobs:
  set-env:
    name: Generate output
    runs-on: ubuntu-latest
    outputs:
      CLUSTER: ${{ steps.expose.outputs.CLUSTER }}
      BRANCH: ${{ steps.expose.outputs.BRANCH }}
    steps:
      - name: DEV Environment 
        if: github.ref_name == 'development' || github.ref_name == 'develop'
        shell: bash
        run: |
          echo "CLUSTER=dev" >> "$GITHUB_ENV"
      
      - name: STG Environment
        if: github.ref_name == 'stage'
        shell: bash
        run: |
          echo "CLUSTER=stg" >> "$GITHUB_ENV"
      
      - name: PRD Environment
        if: github.ref_name == 'master' || github.ref_name == 'main'
        shell: bash
        run: |
          echo "CLUSTER=prd" >> "$GITHUB_ENV"
      
      - name: expose ENV for branch ${{ github.ref_name }}
        id: expose
        shell: bash
        run: |
            echo "CLUSTER=${{ env.CLUSTER }}" >> $GITHUB_OUTPUT
            echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_OUTPUT